### ISSUE TITLE
How do you add the CiviCRM Menu?

### ISSUE THREAD

**Issue by sleewok** [compucorp/shoreditch-companion-d7-theme#3]
We do not have the CiviCRM menu on non-civi pages. How do you get it to show up? I followed the steps to install the companion.

**Comment by Stoob** [comment]
I don't think that's something this theme or the extension does.  But if you are using Drupal you can use this module: https://www.drupal.org/project/civimenu @sleewok

**Comment by jamienovick** [comment]
Thanks @Stoob yes thats correct. Thanks @Stoob
