### ISSUE TITLE
Can it be enhanced to style Webforms and add a sidebar?

### ISSUE THREAD

**Issue by Stoob** [compucorp/shoreditch-companion-d7-theme#4]
This theme looks great with Shoreditch (of course)!  But I would like it very much if:

1. this theme could also style Drupal Webforms (that are integrated with CiviCRM) because we use this in conjunction with Civi for streamlined data entry. (see example screenshot) 

2. it had a sidebar (no real preference on which side, maybe right would be best) because we enjoy using the Recent Items block in Drupal 

Is this work you would be interested in doing?  Sponsorship available.

Thanks! @jamienovick 

![sd-companion-theme](https://user-images.githubusercontent.com/1683473/70830303-c084eb80-1da4-11ea-9e65-67d1fa7ab7bc.png)

**Comment by jamienovick** [comment]
Hey Mr, have sent you an email, best :)

**Comment by jmcclelland** [comment]
I'm curious to know what the answer to these questions was!
